services:

  nginx-fpm-laravel-dev:
    container_name: ${APP_NAME}_dev
    extends:
      file: common-laravel.yml
      service: nginx-fpm-laravel
    build:
      context: .
      dockerfile: laravel-dev.Dockerfile
      args:
        - APP_ENV=${APP_ENV}
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./src-dev:/var/www
    profiles:
      - dev

  nginx-fpm-laravel-test:
    container_name: ${APP_NAME}_test
    extends:
      file: common-laravel.yml
      service: nginx-fpm-laravel
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./storage-${APP_ENV}:/var/www/storage/app
    profiles:
      - test

  nginx-fpm-laravel-staging:
    container_name: ${APP_NAME}_staging
    extends:
      file: common-laravel.yml
      service: nginx-fpm-laravel
    volumes:
      - ./storage-${APP_ENV}:/var/www/storage/app
    profiles:
      - staging

  nginx-fpm-laravel-production:
    container_name: ${APP_NAME}_production
    extends:
      file: common-laravel.yml
      service: nginx-fpm-laravel
    volumes:
      - ./storage-${APP_ENV}:/var/www/storage/app
    profiles:
      - production


networks:
  default:
    external: true
    name: ${SHARED_NETWORK_NAME}
