date.timezone=UTC
display_errors=Off
display_startup_errors=Off
log_errors=On
error_log=/var/log/php/errors.log
error_reporting=E_ALL
upload_max_filesize=80M
post_max_size=80M
memory_limit=256M
variables_order=EGPCS
