version: '3.9'

services:

  nginx-pm:
    #FIXME latest can b dangerous,have broken stuff b4, should be a set build
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - ${PORT_NGINX_PM}:81 #web console
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx-pm-data:/data
      # add custom config in /data/nginx/custom
      # https://nginxproxymanager.com/advanced-config/#custom-nginx-configurations

  portainer: #inner port :9000
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./portainer-readonly/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data

  mysql8: #inner port :3306
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql8-data:/var/lib/mysql
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped

  phpmyadmin: #inner port :80
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 0

  laravel-builder:
    build:
      context: .
      dockerfile: builder.Dockerfile
    volumes:
      - ./laravel-${APP_ENV}:/usr/src
    working_dir: /usr/src
    entrypoint: ./entrypoint-builder.sh
    profiles:
      - test
      - staging
      - production

  laravel-server: #inner port :8000
    build:
      context: .
      dockerfile: laravel.Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - ./laravel-storage-app:/usr/src/storage/app
    restart: unless-stopped
    working_dir: /usr/src
    entrypoint: ./entrypoint-laravel.sh
