version: '3.9'

services:

  nginx-pm:
    #FIXME latest can b dangerous,have broken stuff b4, should be a set build
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - ${PORT_NGINX_PM}:81 #web console
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx-pm-data:/data
      # add custom config in /data/nginx/custom
      # https://nginxproxymanager.com/advanced-config/#custom-nginx-configurations


  portainer: #inner port :9000
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./portainer-readonly/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data


  mysql8: #inner port :3306
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql8-data:/var/lib/mysql
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped


  phpmyadmin: #inner port :80
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 0


  laravel-builder:
    build:
      context: .
      dockerfile: docker/builder.Dockerfile
    volumes:
      - ./laravel-${APP_ENV}:/usr/src
    user: www-data
    working_dir: /usr/src
    entrypoint: ./entrypoint-builder.sh


  nginx-fpm-laravel: #inner port :80
    container_name: nfl-${APP_NAME}
    build:
      context: .
      dockerfile: docker/nginx-fpm-laravel.Dockerfile
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
    restart: unless-stopped
    user: www-data
    working_dir: /var/www
    entrypoint: ./entrypoint.sh
    volumes:
      - ./nfl-${APP_ENV}-storage:/var/www/storage/app
