version: '3.9'

services:

  nginx-pm:
    extends:
      file: common.yml
      service: nginx-pm

  mysql8:
    extends:
      file: common.yml
      service: mysql8

  phpmyadmin:
    extends:
      file: common.yml
      service: mysql8
    ports:
      - ${PORT_PMA}:80 #web console
    depends_on:
      - mysql8
    profiles:
      - test

  phpmyadmin:
    extends:
      file: common.yml
      service: mysql8
    depends_on:
      - mysql8
    profiles:
      - staging
      - production

networks:
  default:
    external: true
    name: ${SHARED_NETWORK_NAME}
