version: '3.9'

services:

  laravel-server-test:
    extends:
      file: common.yml
      service: laravel-builder
    ports:
      - ${PORT_LARAVEL}:8000
    profiles:
      - test

  laravel-server-production:
    extends:
      file: common.yml
      service: laravel-builder
    ports:
      - ${PORT_LARAVEL}:8000
    profiles:
      - production

networks:
  default:
    external: true
    name: ${SHARED_NETWORK_NAME}
