version: '3.9'

services:

  mysql8:
    image: mysql:8.0
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql8-data:/var/lib/mysql
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped
    profiles:
      - mysql8

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PORT_PMA}:80 #web console
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 0
    depends_on:
      - mysql8
    profiles:
      - phpmyadmin

  laravel-test:
    build:
      context: .
      dockerfile: test.Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
    volumes:
      - ./laravel-php-config:/usr/local/etc/php/conf.d
      - ./laravel-storage-app:/usr/src/storage/app
      - ./laravel-test:/usr/src
    restart: unless-stopped
    ports:
      - ${PORT_LARAVEL}:8000
    working_dir: /usr/src
    entrypoint: ./entrypoint-test.sh

networks:
  default:
    external: true
    name: ${SHARED_NETWORK_NAME}
