version: '3.9'

services:

  laravel-builder:
    build:
      context: .
      dockerfile: builder.Dockerfile
    volumes:
      - ./laravel:/usr/src #careful with laravel path, it must be the same as the one in the src/laravel_deploy_command.sh
    working_dir: /usr/src
    entrypoint: ./entrypoint-builder.sh
