version: '3.9'

services:

  nginx-fpm-laravel:
    build:
      context: .
      dockerfile: docker/nginx-fpm-laravel.Dockerfile
      args:
        - APP_ENV=test
    environment:
      - APP_ENV=test
      - APP_DEBUG=true
    volumes:
      - ./laravel-${APP_ENV}-storage-app:/var/www/storage/app
    restart: unless-stopped
    user: www-data
    ports:
      - 9011:80
    working_dir: /var/www

networks:
  default:
    external: true
    name: ${SHARED_NETWORK_NAME}
