services:

  nginx-pm:
    container_name: nginx-pm
    extends:
      file: common-shared.yml
      service: nginx-pm

  mysql8:
    container_name: mysql8
    extends:
      file: common-shared.yml
      service: mysql8

  phpmyadmin:
    container_name: pma
    extends:
      file: common-shared.yml
      service: phpmyadmin
    ports:
      #- ${PORT_PMA}:80 #web console better to not expose this directly, route through nginx
    depends_on:
      - mysql8

networks:
  default:
    external: true
    name: ${SHARED_NETWORK_NAME}
