version: '3.9'

services:

  nginx-pm:
    extends:
      file: common.yml
      service: nginx-pm

  mysql8:
    extends:
      file: common.yml
      service: mysql8

  phpmyadmin:
    extends:
      file: common.yml
      service: mysql8
    depends_on:
      - mysql8

networks:
  default:
    external: true
    name: ${SHARED_NETWORK_NAME}
