services:

  nginx-fpm-laravel-test:
    container_name: ${APP_NAME}_test
    extends:
      file: common.yml
      service: nginx-fpm-laravel
    ports:
      - ${APP_PORT}:80
    profiles:
      - test

  nginx-fpm-laravel:
    container_name: ${APP_NAME}
    extends:
      file: common.yml
      service: nginx-fpm-laravel
    profiles:
      - staging
      - production


networks:
  default:
    external: true
    name: ${SHARED_NETWORK_NAME}
