version: '3.9'

services:

  nginx-pm:
    container_name: nginx-pm
    extends:
      file: common.ym
      service: nginx-pm

  mysql8:
    container_name: mysql8
    extends:
      file: common.ym
      service: mysql8

  phpmyadmin-test:
    container_name: pma-test
    extends:
      file: common.ym
      service: phpmyadmin
    ports:
      - ${PORT_PMA}:80 #web console
    depends_on:
      - mysql8
    profiles:
      - test

  phpmyadmin:
    container_name: pma
    extends:
      file: common.ym
      service: phpmyadmin
    depends_on:
      - mysql8
    profiles:
      - staging
      - production

networks:
  default:
    external: true
    name: ${SHARED_NETWORK_NAME}
