version: '3.9'

services:

  laravel-server:
    build:
      context: .
      dockerfile: laravel.Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
    volumes:
      - ./laravel-php-config:/usr/local/etc/php/conf.d
      - ./laravel-storage-app:/usr/src/storage/app
    restart: unless-stopped
    ports:
      - ${PORT_LARAVEL}:80
    working_dir: /usr/src
    entrypoint: ./entrypoint-laravel.sh


networks:
  default:
    external: true
    name: ${SHARED_NETWORK_NAME}
