version: '3.9'

services:

  nginx-pm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - ${PORT_NGINX_PM}:81  #web console
      - '443:443'
    volumes:
      - ./nginx-pm-data:/data
      - ./letsencrypt:/etc/letsencrypt
      #- /nginx-config/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx-config/custom-config.conf:/etc/nginx/conf.d/custom-config.conf


  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - ${PORT_PORTAINER}:9000  #web console
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./portainer-readonly/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    depends_on:
      - nginx-pm


  mysql8:
    image: mysql:8.0
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./mysql8-data:/var/lib/mysql
      - ./mysql8-config:/etc/mysql/conf.d
    restart: unless-stopped


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PORT_PMA}:80  #web console
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 0
    depends_on:
      - mysql8

networks:
  default:
    external: true
    name: ${SHARED_NETWORK_NAME}
