[program:laravel-reverb]
command=php /var/www/artisan reverb:start
numprocs=1
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/laravel-reverb.err.log
stdout_logfile=/var/log/supervisor/laravel-reverb.out.log
user=www-data
priority=3
