[program:laravel-queue]
command=php /var/www/artisan queue:work
numprocs=1
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/laravel-queue.err.log
stdout_logfile=/var/log/supervisor/laravel-queue.out.log
user=www-data
priority=4
