[program:laravel-websockets]
command=php /var/www/artisan websockets:serve
numprocs=1
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/laravel-websockets.err.log
stdout_logfile=/var/log/supervisor/laravel-websockets.out.log
user=www-data
priority=7
