[program:laravel-octane]
command=php /var/www/artisan octane:start
numprocs=1
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/laravel-octane.err.log
stdout_logfile=/var/log/supervisor/laravel-octane.out.log
user=www-data
priority=8
