[program:laravel-horizon]
command=php /var/www/artisan horizon
numprocs=1
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/laravel-horizon.err.log
stdout_logfile=/var/log/supervisor/laravel-horizon.out.log
user=www-data
priority=5
