[program:laravel-scheduler]
command=php /var/www/artisan schedule:work
numprocs=1
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/laravel-scheduler.err.log
stdout_logfile=/var/log/supervisor/laravel-scheduler.out.log
user=www-data
priority=6
